"""create templates

Revision ID: 1a01f2024af9
Revises: 3de5b5190a81
Create Date: 2026-01-27 16:51:33.956078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a01f2024af9'
down_revision: Union[str, Sequence[str], None] = '3de5b5190a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('shapes_json', sa.Text(), nullable=False),
    sa.Column('canvas_width', sa.String(), nullable=False),
    sa.Column('canvas_height', sa.String(), nullable=False),
    sa.Column('background_image', sa.Text(), nullable=True),
    sa.Column('logo_placement_json', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_brand_id'), 'templates', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_brand_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
