"""add templates and draft media

Revision ID: 3de5b5190a81
Revises: 9169533ff729
Create Date: 2026-01-27 16:33:24.648371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3de5b5190a81'
down_revision: Union[str, Sequence[str], None] = '9169533ff729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'hashtags')
    op.drop_column('content_items', 'scheduled_at')
    op.drop_column('content_items', 'structured')
    op.drop_column('content_items', 'last_error')
    op.drop_column('content_items', 'body_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_items', sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
